(function(){const c=document.createElement("link").relList;if(c&&c.supports&&c.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const s of e.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();document.addEventListener("DOMContentLoaded",()=>{const a=document.querySelector(".projects-list"),c=document.querySelector(".load-more-button"),o=[{imgSrc1x:"../img/energy-1x.jpg",imgSrc2x:"../img/energy-2x.jpg",alt:"energy projects",stack:"React, JavaScript, Node JS, Git",title:"ENERGY FLOW WEBSERVICE",link:"https://github.com/Kate-Iva/portfolio-project-14"},{imgSrc1x:"../img/fruitbox-1x.jpg",imgSrc2x:"../img/fruitbox-2x.jpg",alt:"fruitbox projects",stack:"React, JavaScript, Node JS, Git",title:"FRUITBOX ONLINE STORE",link:"https://github.com/Kate-Iva/portfolio-project-14"},{imgSrc1x:"../img/jewelry-1x.jpg",imgSrc2x:"../img/jewelry-2x.jpg",alt:"jewelry projects",stack:"React, JavaScript, Node JS, Git",title:"CHEGO JEWELRY WEBSITE",link:"https://github.com/Kate-Iva/portfolio-project-14"},{imgSrc1x:"../img/mimino-1x.jpg",imgSrc2x:"../img/mimino-2x.jpg",alt:"mimino projects",stack:"React, JavaScript, Node JS, Git",title:"MIMINO WEBSITE",link:"https://github.com/Kate-Iva/portfolio-project-14"},{imgSrc1x:"../img/power-1x.jpg",imgSrc2x:"../img/power-2x.jpg",alt:"power projects",stack:"React, JavaScript, Node JS, Git",title:"POWER PULSE WEBSERVICE",link:"https://github.com/Kate-Iva/portfolio-project-14"},{imgSrc1x:"../img/starlight-1x.jpg",imgSrc2x:"../img/starlight-2x.jpg",alt:"starlight projects",stack:"React, JavaScript, Node JS, Git",title:"STARLIGHT STUDIO LANDING PAGE",link:"https://github.com/Kate-Iva/portfolio-project-14"},{imgSrc1x:"../img/vyshyvanka-1x.jpg",imgSrc2x:"../img/vyshyvanka-2x.jpg",alt:"vyshyvanka projects",stack:"React, JavaScript, Node JS, Git",title:"VYSHYVANKA VIBES LANDING PAGE",link:"https://github.com/Kate-Iva/portfolio-project-14"}];let i=0;const t=3,e=()=>{const s=Math.min(i+t,o.length);for(let l=i;l<s;l++){const r=o[l],n=document.createElement("li");n.classList.add("projects-list-items"),n.innerHTML=`
                <picture>
                    <source srcset="${r.imgSrc1x} 1x", 
                    ${r.imgSrc2x} 2x />
                    <img src="${r.imgSrc1x}" alt="${r.alt}" class="projects-item-img">
                </picture>
                <div class="tech-stack">${r.stack}</div>
                <div class="projects-item-conteiner">
                    <div class="projects-item-title">${r.title}</div>
                    <a href="${r.link}" class="projects-btn" target="_blank">VISIT
                        <svg class="projects-icon" width="24" height="24">
                            <use href="../img/icons.svg#icon-arrow-visit"></use>
                        </svg>
                    </a>
                </div>
            `,a.appendChild(n)}i+=t,i>=o.length&&(c.style.display="none")};c.addEventListener("click",e)});const p={accordionWrappers:document.querySelectorAll(".ac"),acList:document.querySelector(".accordion-container")};function g(a){const c=a.target;if(c.closest(".ac-panel"))return;const i=c.closest(".ac"),t=document.querySelector(".is-active");t&&t.id!==i.id&&t.classList.remove("is-active"),i.classList.toggle("is-active")}p.acList.addEventListener("click",g);
//# sourceMappingURL=commonHelpers.js.map
